# Generated by Django 3.0.4 on 2020-10-13 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil_empresa', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='telefono',
            field=models.IntegerField(default=0, max_length=9),
        ),
    ]
