# Generated by Django 3.0.4 on 2020-10-13 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil_empresa', '0002_auto_20201012_2103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='telefono',
            field=models.IntegerField(max_length=9),
        ),
    ]
